// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:promodoro/data/models/alarm_model.dart';
import 'package:promodoro/data/models/daily_stat.dart';
import 'package:promodoro/data/models/pomodoro_stats.dart';
import 'package:promodoro/data/models/settings_model.dart';
import 'package:promodoro/data/models/theme_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AlarmModelAdapter());
    registerAdapter(DailyStatAdapter());
    registerAdapter(PomodoroStatsAdapter());
    registerAdapter(SettingsModelAdapter());
    registerAdapter(ThemeModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AlarmModelAdapter());
    registerAdapter(DailyStatAdapter());
    registerAdapter(PomodoroStatsAdapter());
    registerAdapter(SettingsModelAdapter());
    registerAdapter(ThemeModelAdapter());
  }
}
